
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftLPleftLCrightRPrightRCBODY BSLASH CHARACTER COLON COMMA COMMENTS CREATEDATA CREATESERVER DQUOTE EQUAL FROM HTTPGET ID INT JSON LC LP OBJECT PERIOD PLUS PORT RC READDATA RP SEMICOLON SETROUTES SLASH START STRING UNKNOWN URLExp : ID EQUAL JSON COLON LC RC SEMICOLONExp : ID EQUAL JSON COLON LC Inside RC SEMICOLONInside : STRING COLON ObjectParamInsideRec : STRING COLON ObjectParam COMMA InsideObjectParam : IDObjectParam : INTObjectParam : STRINGExp : ID SEMICOLONExp : ID EQUAL CREATESERVER LP PORT EQUAL INT RP SEMICOLONExp : ID COLON START SEMICOLON'
    
_lr_action_items = {'ID':([0,20,],[2,25,]),'$end':([1,5,11,18,22,28,],[0,-8,-10,-1,-2,-9,]),'EQUAL':([2,13,],[3,17,]),'SEMICOLON':([2,8,14,19,27,],[5,11,18,22,28,]),'COLON':([2,6,16,],[4,9,20,]),'JSON':([3,],[6,]),'CREATESERVER':([3,],[7,]),'START':([4,],[8,]),'LP':([7,],[10,]),'LC':([9,],[12,]),'PORT':([10,],[13,]),'RC':([12,15,23,24,25,26,],[14,19,-7,-3,-5,-6,]),'STRING':([12,20,],[16,23,]),'INT':([17,20,],[21,26,]),'RP':([21,],[27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Exp':([0,],[1,]),'Inside':([12,],[15,]),'ObjectParam':([20,],[24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Exp","S'",1,None,None,None),
  ('Exp -> ID EQUAL JSON COLON LC RC SEMICOLON','Exp',7,'p_object_def_empty','ViSeParser.py',19),
  ('Exp -> ID EQUAL JSON COLON LC Inside RC SEMICOLON','Exp',8,'p_object_def','ViSeParser.py',25),
  ('Inside -> STRING COLON ObjectParam','Inside',3,'p_inside_object','ViSeParser.py',31),
  ('InsideRec -> STRING COLON ObjectParam COMMA Inside','InsideRec',5,'p_inside_rec','ViSeParser.py',36),
  ('ObjectParam -> ID','ObjectParam',1,'p_object_param_id','ViSeParser.py',40),
  ('ObjectParam -> INT','ObjectParam',1,'p_object_param_int','ViSeParser.py',45),
  ('ObjectParam -> STRING','ObjectParam',1,'p_object_param_string','ViSeParser.py',50),
  ('Exp -> ID SEMICOLON','Exp',2,'p_variable','ViSeParser.py',55),
  ('Exp -> ID EQUAL CREATESERVER LP PORT EQUAL INT RP SEMICOLON','Exp',9,'p_exp_create_server','ViSeParser.py',66),
  ('Exp -> ID COLON START SEMICOLON','Exp',4,'p_server_start','ViSeParser.py',72),
]
