
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BODY BSLASH CHARACTER COLON COMMA COMMENTS CREATEDATA CREATESERVER DQUOTE EQUAL FROM HTTPGET ID INT JSON LC LP OBJECT PERIOD PLUS PORT RC READDATA RP SEMICOLON SETROUTES SLASH START STRING UNKNOWN URLExp : ID EQUAL JSON COLON LC RC SEMICOLONExp : ID EQUAL JSON COLON LC Inside RC SEMICOLONExp : ID EQUAL JSON COLON LC InsideRec RC SEMICOLONInside :  STRING COLON STRING InsideRec : Inside COMMA Inside COMMA InsideExp : ID SEMICOLONExp : ID EQUAL CREATESERVER LP PORT EQUAL INT RP SEMICOLONExp : ID COLON START SEMICOLONExp : ID EQUAL HTTPGET LP URL EQUAL STRING RP SEMICOLONExp : HTTPGET LP URL EQUAL STRING RP SEMICOLONExp : ID EQUAL ID COLON SETROUTES LP URL EQUAL STRING RP SEMICOLONExp : ID COLON READDATA LP BODY EQUAL ID RP SEMICOLONExp : ID COLON CREATEDATA LP OBJECT EQUAL ID RP SEMICOLON'
    
_lr_action_items = {'ID':([0,4,38,39,],[2,8,49,50,]),'HTTPGET':([0,4,],[3,11,]),'$end':([1,6,20,42,51,53,55,63,64,65,66,69,],[0,-6,-8,-1,-10,-2,-3,-7,-9,-12,-13,-11,]),'EQUAL':([2,15,26,27,28,29,41,],[4,23,36,37,38,39,52,]),'SEMICOLON':([2,12,32,40,43,45,57,58,59,60,67,],[6,20,42,51,53,55,63,64,65,66,69,]),'COLON':([2,8,9,35,],[5,16,17,46,]),'LP':([3,10,11,13,14,24,],[7,18,19,21,22,31,]),'JSON':([4,],[9,]),'CREATESERVER':([4,],[10,]),'START':([5,],[12,]),'READDATA':([5,],[13,]),'CREATEDATA':([5,],[14,]),'URL':([7,19,31,],[15,27,41,]),'SETROUTES':([16,],[24,]),'LC':([17,],[25,]),'PORT':([18,],[26,]),'BODY':([21,],[28,]),'OBJECT':([22,],[29,]),'STRING':([23,25,37,44,46,52,62,],[30,35,48,35,56,61,35,]),'RC':([25,33,34,56,68,],[32,43,45,-4,-5,]),'RP':([30,47,48,49,50,61,],[40,57,58,59,60,67,]),'COMMA':([33,54,56,],[44,62,-4,]),'INT':([36,],[47,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Exp':([0,],[1,]),'Inside':([25,44,62,],[33,54,68,]),'InsideRec':([25,],[34,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Exp","S'",1,None,None,None),
  ('Exp -> ID EQUAL JSON COLON LC RC SEMICOLON','Exp',7,'p_object_def_empty','ViSeParser.py',19),
  ('Exp -> ID EQUAL JSON COLON LC Inside RC SEMICOLON','Exp',8,'p_object_def','ViSeParser.py',25),
  ('Exp -> ID EQUAL JSON COLON LC InsideRec RC SEMICOLON','Exp',8,'p_object_def_rec','ViSeParser.py',31),
  ('Inside -> STRING COLON STRING','Inside',3,'p_inside_object','ViSeParser.py',37),
  ('InsideRec -> Inside COMMA Inside COMMA Inside','InsideRec',5,'p_inside_rec','ViSeParser.py',42),
  ('Exp -> ID SEMICOLON','Exp',2,'p_variable','ViSeParser.py',47),
  ('Exp -> ID EQUAL CREATESERVER LP PORT EQUAL INT RP SEMICOLON','Exp',9,'p_exp_create_server','ViSeParser.py',58),
  ('Exp -> ID COLON START SEMICOLON','Exp',4,'p_server_start','ViSeParser.py',64),
  ('Exp -> ID EQUAL HTTPGET LP URL EQUAL STRING RP SEMICOLON','Exp',9,'p_communicate_id','ViSeParser.py',73),
  ('Exp -> HTTPGET LP URL EQUAL STRING RP SEMICOLON','Exp',7,'p_communicate','ViSeParser.py',78),
  ('Exp -> ID EQUAL ID COLON SETROUTES LP URL EQUAL STRING RP SEMICOLON','Exp',11,'p_server_sets','ViSeParser.py',84),
  ('Exp -> ID COLON READDATA LP BODY EQUAL ID RP SEMICOLON','Exp',9,'p_server_reads','ViSeParser.py',93),
  ('Exp -> ID COLON CREATEDATA LP OBJECT EQUAL ID RP SEMICOLON','Exp',9,'p_server_creates','ViSeParser.py',103),
]
